USE sakila; 

# 1 List the number of films per category 

SELECT c.name, COUNT(f.film_id) AS film_count
FROM film AS f
INNER JOIN film_category AS fc 
ON f.film_id = fc.film_id
INNER JOIN category AS c 
ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY film_count DESC;

# 2 Retrieve the store ID, city, and country for each store

SELECT s.store_id, c.city, co.country 
FROM store AS s 
INNER JOIN address AS a
ON s.address_id = a.address_id 
INNER JOIN city AS c 
ON a.city_id = c.city_id 
INNER JOIN country as co 
ON c.country_id = co.country_id 
GROUP BY s.store_id; 

# 3 Calculate the total revenue generated by each store in dollars

SELECT sto.store_ID, SUM(p.amount) AS revenue 
FROM payment as p 
INNER JOIN staff as s
ON p.staff_id = s.staff_id 
INNER JOIN store as sto
ON s.store_id = sto.store_id  
GROUP BY sto.store_id
ORDER BY revenue DESC; 

# 4 Determine the average running time of films for each category.

SELECT c.name, AVG(f.length)
FROM film AS f 
INNER JOIN film_category AS fc 
ON f.film_id = fc.film_id 
INNER JOIN category AS c
ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY AVG(f.length) DESC; 
